#!/bin/bash

./configure --prefix=$HOME/local/
# Edit completions/Makefile to replace \<reptyr with _reptyr
make
make install
# Copy missing completions (like tmux) from the previous install:
#   if you did not run "rm -rf $HOME/local/share/bash-completion", you don't need to do anything
#   if you did, copy from the backup
