#!/bin/bash
# Was getting the following error:
#
#    $HOME/local/bin/ld: htop-CRT.o: undefined reference to symbol 'cbreak'
#    $HOME/local/lib/libtinfo.so.5: error adding symbols: DSO missing from command line
#
# Fixed it by adding -ltinfow to the final linkage
