#!/bin/bash
# Use install-GUI.sh
# Select custom directory $HOME/local/opt/intel/intel-composer_xe-2015.0.090/
#   note that one needs both subdirs
mkdir  $HOME/local/opt/intel/intel-composer_xe-2015.0.090/composer_xe_2015.0.090/bin/intel64/../../Licenses
cd  $HOME/local/opt/intel/intel-composer_xe-2015.0.090/composer_xe_2015.0.090/bin/intel64/../../Licenses
ln -s $HOME/intel/licenses/SON.lic .
