#!/bin/bash

tar -xzvf ~/.downloads/llvm.tgz
cd <llvm-version>/tools
tar -xzvf ~/.downloads/clang.tgz
mv <clang-version> clang
tar -xzvf ~/.downloads/lldb.tgz
mv <lldb-version> lldb
cd ..
cd projects
ln -s /home/aprokop/code/packages/system/libcxx .
ln -s /home/aprokop/code/packages/system/libcxxabi .
cd ..
mkdir build
cd build
module load gcc/4.9.2
export CC=clang
export CXX=clang++
cmake -DCMAKE_INSTALL_PREFIX=/home/aprokop/local/opt/llvm-3.5.0 -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_ENABLE_LIBCXX=ON -G Ninja ..
make
# To install LLDB, had to edit tools/lldb/scripts/cmake_install.cmake:36 and change lib/python2.6 to lib64/python2.6
make install

# Install analyzer tools
cd ..
cd tools/clang/tools
mkdir ~/local/opt/llvm-3.5.0/tools
cp -r scan-{build,view} ~/local/opt/llvm-3.5.0/tools
cd ~/local/opt/llvm-3.5.0/bin
ln -s ../tools/scan-view/scan-view .
ln -s ../tools/scan-build/scan-build .
