#!/bin/sh
# Needs update versions of numpy, scipy and nose
python setup.py build
PYTHONPATH=$HOME/local/opt/matplotlib/lib64/site-packages:$PYTHONPATH python setup.py install --prefix=$HOME/local/opt/matplotlib
