#!/bin/bash
LDFLAGS="-ltinfow" ./configure --prefix=/home/aprokop/local
./configure
make --trace
# make fails in the linking stage because -ltinfo goes before -lncursesw
# add -ltinfo at the end of the linking command, and rerun linking manually
