#!/bin/bash
YAML_VERSION=upstream

module load gcc/5.1.0
module load boost/1.57.0-cxx
cmake -DCMAKE_INSTALL_PREFIX=$HOME/local/opt/yaml-cpp-$YAML_VERSION -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_FLAGS="-Wl,-rpath=$HOME/local/o
pt/gcc-5.1.0/lib64" ../
make
make install
